### ISSUE TITLE
Move Deprecated Products and Formats to FAQ

### ISSUE THREAD

**Issue by cmungall** [geneontology/geneontology.github.io#106]
I don't think archived products + deprecated formats should be grouped together, or linked from the top level menu

Archived go-slims should be it's own page. No top level menu link. Just link from subsets page.

GAF 2.0 should not be listed as an archived products.

**Comment by suzialeksander** [comment]
I don't think we (@pgaudet) liked the deprecated info under Downloads, but grouped them in order to not have a stub page for MySQL, CVS, FTP.

I'm happy to move go-slims. I'd actually like to split the current Subset Guide to put the subsets/antislims/(and now archives) downloads under the Downloads menu item, there will be a new menu item anyway when @lpalbou  works on #83 - any objections?

For the rest of what's on the current depreciated page, we can 
*  move info on depreciated ontology files & formats to a new page linked on the bottom of the Download ontology page, and annots on the  the annots 
* Put ^these^ links be on the Downloads overview page in the appropriate section

Then, where would it be most reasonable to find Archived MySQL database files/Repositories/Databases and schemas? Stub page anyway, linked from _???_

GAF 2.0 is an outlier because it's still used, but we don't want to encourage use of it over 2.1, and aren't GAFs going away in April? I can move it or link it back to the GAF formats/2.1 page.

**Comment by suzialeksander** [comment]
Building on above,  Cross-references of external classification systems to GO (/download-mappings/) is mostly download links as well.  Not sure if this should stay or also be partially moved to Downloads.

**Comment by suzialeksander** [comment]
Suggestion from #84: Move Deprecated Products and Formats to FAQ

**Comment by lpalbou** [comment]
@cmungall which versions of the GAF files do we provide in the current archive in zenodo ? If the GAF 2.1 is used then probably the GAF 2.0 should be indeed considered as deprecated ?

Deprecated formats and Archive are now two separate pages but they are still linked from the top level menu. Do we really want to remove those easy links ? Most users won't have the patience to go through the pages to find those if they need them.

@suzialeksander as it is, the FAQ is very messy and not great to search or reference. I would strongly advised against it at this stage

**Comment by lpalbou** [comment]
@kltm @cmungall do you know which GAF version we store in the Zenodo archives ?

[Edit]: Checking on current.geneontology.org, it seems that all GAFs are 2.1 since 2018-03-10. There is only one release prior to that (2018-03-06) had some problems anyhow.
