### ISSUE TITLE
GO home page suggested edits

### ISSUE THREAD

**Issue by RLovering** [geneontology/geneontology.github.io#151]
Hi

please could the GO enrichment title and box be moved down slightly so that the top of this is in line with the top of the main text, currently it looks very squashed up underneath the main page title (on mozilla) 
<img width="1129" alt="screenshot 2019-03-02 at 09 30 38" src="https://user-images.githubusercontent.com/12080010/53680085-50eeb580-3cd6-11e9-870f-39a8f72c6147.png">

Also following from the news section github ticket which is now closed (https://github.com/geneontology/geneontology.github.io/issues/52#issuecomment-427172446), please could you consider  adding a twitter feed to the home page. ( I am sure you are aware of this but if not see our webpage which is also drupal based.) https://www.ucl.ac.uk/cardiovascular/research/pre-clinical-and-fundamental-science/functional-gene-annotation )

I think you will get a lot more twitter followers if you have the feed actually on the home page, rather than expecting people to see the small twitter icon at the top and click on this to see what is there

Thanks

Ruth

**Comment by lpalbou** [comment]
@RLovering I answered the twitter proposal on the original ticket.

For the positioning of the GO Enrichment Analysis box, it really depends of the size of your screen. This is how it shows on my Mac:
<img width="1903" alt="screen shot 2019-03-04 at 12 17 11 am" src="https://user-images.githubusercontent.com/24249870/53719441-e5f6c900-3e12-11e9-9653-61d48fd11389.png">

And if I reduce:
<img width="1154" alt="screen shot 2019-03-04 at 12 18 01 am" src="https://user-images.githubusercontent.com/24249870/53719471-feff7a00-3e12-11e9-9871-4d07ecc7bfe9.png">

I can easily align the GO enrichment box with the text:
<img width="1150" alt="screen shot 2019-03-04 at 12 16 14 am" src="https://user-images.githubusercontent.com/24249870/53719526-30784580-3e13-11e9-8925-567d528abf56.png">

But, if you go back to a larger width, it feels like the GO enrichment section is push down:

<img width="1920" alt="screen shot 2019-03-04 at 12 20 48 am" src="https://user-images.githubusercontent.com/24249870/53719593-687f8880-3e13-11e9-9b72-ee9983b0236c.png">

Rather than aligning the texts, how about this intermediary:

Intermediary width:
<img width="1152" alt="screen shot 2019-03-04 at 12 27 57 am" src="https://user-images.githubusercontent.com/24249870/53720004-7aadf680-3e14-11e9-8710-ec1af0cdd906.png">

Still ok at larger width:
<img width="1908" alt="screen shot 2019-03-04 at 12 27 47 am" src="https://user-images.githubusercontent.com/24249870/53719974-64079f80-3e14-11e9-90d2-569d0e601f61.png">

**Comment by RLovering** [comment]
Hi

This is obviously a question of tasten(and screen size ; I don't see much difference between the current and the intermediatory views. I think it looks neater with the top of the first text and the GO enrichment anlysis text aligned, and based on the fact that pages like google have a lot of empty space I think this looks fine. In order to use the search field people need to have that area in view and so they would still see the GO enrichment box. The problem with us old people is that our eye sight means we want big text, especially with our eye sight deteriorating every day so that our prescription glasses can't keep up with our needs.

This is your choice, please close the ticket, it was just a personal opinion on the page. 

I should have also said it does look very good, it must have taken a long time to do and it brings GO into the 21st century. Thanks for your work on this

Ruth

**Comment by lpalbou** [comment]
We also justify the mission statement and made it the same width at the title & search bar in hoping it will help the eye distinguishing those two sections.
