### ISSUE TITLE
Broken links in menu on http://current.geneontology.org/products/pages/downloads.html

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#233]
The following menu items on http://current.geneontology.org/products/pages/downloads.html should be removed or changed as a short-term solution before headers are redone to match rest of website (#184 #198 #199) :

* GOC logo image: goes to http://current.geneontology.org/products/pages/index.html#home, should go to http://geneontology.org/
**Documentation**
 * Introduction: BROKEN, should go to http://geneontology.org/docs/introduction-to-go-resource/
 * FAQs: good 
 * Ontology: good 
 * Annotation: good 
 * Annotation Extension: BROKEN, remove
 * GO database: BROKEN, remove
 * File Format guide: BROKEN, should go to http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/
 * Annotation Tools, Downloads, and Beyond: BROKEN, should go to http://geneontology.org/docs/tools-overview/
 * Contributing to GO: good
 * Submitting GO Annotations: BROKEN, should go to http://geneontology.org/docs/contributing-to-go/
 * Other useful information: BROKEN, remove
**Downloads**
all OK, no changes
**Community**
 * Overview: BROKEN, http://geneontology.org/docs/ontology-documentation/
 * GO Projects: BROKEN, remove
 * Collaborations: BROKEN, should go to http://geneontology.org/docs/collaborations/
 * GO Wiki: good
 * GO Contributors: good 
 * GO mailing lists: remove
**Tools**
all OK
**About**
all OK
**Contact us** : broken, should go to http://help.geneontology.org/

thanks

**Comment by lpalbou** [comment]
This page is created by the pipeline and not this site. This is also linked to https://github.com/geneontology/geneontology.github.io/issues/199 where it's difficult to have a fully compatible style since this page is external.

Favored fix: create a download page inside this site, but i wanted to avoid such dynamic pages as the tech behind was really not made for that. 2-3 days work, possibly more depending of how clean we want it. See https://github.com/geneontology/geneontology.github.io/issues/199.

Quick fix: i can edit the page generator in the pipeline. But I don't know like the GO site referencing external pages. Probably very bad for SEO (search) too.

**Comment by suzialeksander** [comment]
Since this page is still accessible, fixing what I can. Trying to match main site menu
About/Ontology/Annotations/Downloads/Help

Worth keeping: tools links?

**Comment by suzialeksander** [comment]
Changed header to match rest of site, so at least the broken items are gone.  Left the redundant link to Home, as on my Chrome (may have ad blockers enabled by default??) the GO logo with the home logo does not appear on the Downloads page (works on rest of site).

Still lacks social media and alliance links, but adding new stuff should be a new ticket.
