### ISSUE TITLE
Handover of main GO website

### ISSUE THREAD

**Issue by lpalbou** [geneontology/geneontology.github.io#293]
Transfer to @kltm . Ask questions :)

More seriously, some useful links:
- [x] [Indexing of site pages for search](https://github.com/geneontology/geneontology.github.io#indexing-the-pages); I believe this has been exhausted -kltm
- [x] [Archive page](http://release.geneontology.org) | [Code](https://github.com/lpalbou/aws-js-s3-explorer); now https://github.com/geneontology/aws-js-s3-explorer with some added notes -kltm
- [x] [Stats page](http://geneontology.org/stats.html) | [Code](https://github.com/geneontology/geneontology.github.io/blob/master/stats.html)
- [x] [SARS-CoV-2](http://geneontology.org/covid-19.html) | [Code](https://github.com/geneontology/geneontology.github.io/blob/master/covid-19.html)
- [ ] [SPARQL page](http://sparql.geneontology.org) | [Code](https://github.com/geneontology/geneontology.github.io/blob/master/sparql.html)
- [ ] [Handling of the menus](https://github.com/geneontology/geneontology.github.io/blob/master/_data/docs.yml)
- [ ] [Ribbon sandbox](http://geneontology.org/ribbon) | [Code](https://github.com/geneontology/geneontology.github.io/blob/master/ribbon.html)

Notes:
* I recommend to link the ribbon sandbox to a traditional subdomain ribbon.geneontology.org @cmungall 
* @kltm I will send you the algolia key by email, remind me if I forget

**Comment by kltm** [comment]
I now have possession of the key. Will start working through README and practice.

**Comment by lpalbou** [comment]
Just for clarity, for the indexing used in the search page 🙂

**Comment by kltm** [comment]
Okay, I can now setup an appropriate ruby/gem environment and run locally. As part of this process, I had to deep six the Gemfile.lock so that my local versions aligned well enough to continue the build. The differences ended up looking like:

```
sjcarbon@moiraine:~/local/src/git/geneontology.github.io[master]$:) diff /tmp/Gemfile.lock Gemfile.lock 
4c4
<     addressable (2.7.0)
---
>     addressable (2.8.0)
13c13
<     ffi (1.15.0)
---
>     ffi (1.15.3)
52c52
<     listen (3.5.1)
---
>     listen (3.6.0)
56,58c56
<     mini_portile2 (2.5.1)
<     nokogiri (1.11.3)
<       mini_portile2 (~> 2.5.0)
---
>     nokogiri (1.12.1-x86_64-linux)
79c77
<   ruby
---
>   x86_64-linux
92c90
<    ruby 2.7.2p137
---
>    ruby 2.5.1p57
95c93
<    2.2.3
---
>    2.2.25
```
Any thoughts on whether it's worth keeping around, or just adding some extra verbiage to say that it might need to be tossed?
I'll add a doc PR, but the only other two points to add to the doc would be needing to install `ruby-dev` (likely just a me/ubuntu thing) and a specific installation of jekyll with `gem install jekyll`.

**Comment by kltm** [comment]
I've played around a little now with algolia and had a few questions:
* Is the GO site currently using "free" version (10k, 10k), or is there an upgraded version back there?
  * Either way, would you know how close to those limits we currently run?
* I notice that there are also "teams" for the applications; would you know if it's possible to turn an application over to a new owner? The algolia docs are a little unclear and seem to be loose with "application" vs "account" (https://www.algolia.com/doc/faq/accounts-billing/how-do-i-transfer-ownership-of-my-account/)
* Assuming that I was going to move the GO index to a different account (might be cleaner, especially if you otherwise use algolia), it looks like all I need is the new secret "server-side" key and to update `_config.yml`; am I missing anything there? Seems pretty easy...

**Comment by lpalbou** [comment]
@lpalbou check if i can transfer algolia account to @kltm

**Comment by kltm** [comment]
@lpalbou I think I now understand Algolia, how it works, how to update, etc. One thing that is still a mystery to me, however, is how the billing works--they're documentation regarding the "free tier" is not great.

Basically, I'm wondering if you had to put in your credit card info, or if it automatically switched over to the "free tier" after the 14-day trial expired. (I've tried forcing the issue upfront, but whatever is going on on that page has caused two different browsers to hang/crash.)

Otherwise, I'll start checking through the rest of the items in your original list to see if everything makes sense.

**Comment by kltm** [comment]
Communicating w/ @lpalbou today, we have taken over the current account to my LBL email address, with the credentials in the usual place. I also have another algolia account setup and ready to go at the shared groups address--we can v/easily switch at any time.

To round out my questions: no credit card needed, automatically converts to "community" tier, and we're currently at ~3.5k queries, or about 1/3 of the way to paying or reconsideration.

**Comment by kltm** [comment]
#### Stats
@lpalbou Looking at https://github.com/geneontology/geneontology.github.io/blob/master/stats.html, it seems to be a straightforward launcher for https://github.com/geneontology/geneontology.github.io/blob/master/js/stats.js, which seems to be straightforward itself. Are there any caveats or gotchas lurking in there? Otherwise, I think I'll just check that on off.

#### COVID-19

Similarly, the COVID-19 page seems to be similar: simple launcher for uncompiled code in another directory. I did note two differences that I wanted to check on. First, there is the ribbon embedding in the covid-19.html page; I assume that it is straightforward and that I can contact @tmushayahama if there are issues. Second, in covid.js, there is a large embedded data object with `covid_data`; is that something that is just static for the life of the page, or is that something that we need to worry about updating?
With those clarifications, I think that all seems clear and straightforward to me.

**Comment by lpalbou** [comment]
Stats: no nothing special, it’s been working without issue. Only thing however you might want to check or alter in the future is that we show the data for all releases. Over time, the columns and labels would be too narrow so you probably want to limit to let’s say the last 2 years ? Another thing is that now the number of added and removed pmids is also added to the go-stats-summary. It’s still new though and didn’t had time to recompute all stats on the releases since 2018, but the more releases you have, the more relevant it will be. The idea is to also show in a graph the consortium work done to add and remove references. I could create a graph using that data, but probably you would activate it only in ~6 months where we have enough data points.

covid: yes you would be able to contact @tmushayahama about the go ribbon and if everything fails to refer to the 2h recorded training (see godev ML). I don’t expect having any trouble there and as it’s loading the ribbon from the NPM/CDN, anytime a new release would be out, it would be directly used by the website. For the data, yes leave it as it is and I don’t suspect this page will be updated more in the future. Important note though, I do believe this should be the template for GO on how to present data for gene sets (eg showing both the ribbon and linking to enrichment analysis for specific sets). @cmungall @thomaspd

**Comment by kltm** [comment]
Cheers--check and check.

A few final items then:

#### sparql page

My read of this is that it is entirely self-contained w/in the html and remote library pull by tags, with no JS that we maintain (that is not in the html), with yasgui being the key element. As such, unless I'm missing something, it's probably the simplest thing here.

Also, just taking this chance to confirm that the bucket `geneontology-public` is under the USC account umbrella.

#### handling of the menus

I believe that this is just a reference to the location of the menus YAML, following usual jekyll/liquid pattern. Unless there are additional details, I think this should be fine.

#### ribbon sandbox

This seems to follow a same pattern as the covid-19 page, but with the JS files containing a few variables and attachments/hooks and the html imports and framing. As with covid-19, it seems straightforward and if I had external issues I'd contact @tmushayahama .

**Comment by lpalbou** [comment]
sparql: yep, by design I made it self contained so we could reuse it easily anywhere; code could be slightly simpler / cleaner, but does the trick. FYI I was coding the possibility to load all sparql queries directly from a GH repo. Could finish that, not so complicated and could be useful for other projects as well as sharing of queries.

`geneontology-public` as well as many go-related buckets are indeed on the USC account. Also did that to reserve those namespaces. @dustine32 if you want a full list

menus: that's correct, you just have to edit the yaml and put the proper anchor/tag to your markdown page

ribbon: yep, not much to say there; you do have the addition of the wc-go-autocomplete web component which is used to translate gene name to gene IDs. as a note, I never had time to code an error handling if you select a gene through the autocomplete which has 0 annotation. It would just do nothing on the ribbon.. where we might want to display something like: no annotation available for xxx.

**Comment by kltm** [comment]
@lpalbou Okay, great--thank you for the information!
