### ISSUE TITLE
geneontology.org/stats.html dropdown needs to include full release date, is missing day

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#407]
The statistics dropdown to choose the release have YYYY-MM, needs to display YYYY-MM-DD.  This is confusing when there are multiple releases in a month, and also goes against our own guidelines for formatting a release version.

[geneontology.github.io/stats.html](https://github.com/geneontology/geneontology.github.io/blob/507521bab4410aa6e333f7bf4936e2f2b3fadd32/stats.html)

![Screenshot 2023-02-09 at 19 02 31](https://user-images.githubusercontent.com/13735608/217981604-916d4903-0093-457d-b0c0-c23206c5f25b.png)

**Comment by suzialeksander** [comment]
@pkalita-lbl is this something you can do easily/quickly? Instead of YYYY-MM the dropdown needs to display  YYYY-MM-DD

**Comment by kltm** [comment]
The site link is https://geneontology.github.io/stats.html
Noting that the issue is likely:
https://github.com/geneontology/geneontology.github.io/blob/507521bab4410aa6e333f7bf4936e2f2b3fadd32/js/stats.js#L702
The data already seems to be there in http://current.geneontology.org/release_stats/aggregated-go-stats-summaries.json

The issue is more along the lines of how does it get changed and how does one recompile?

**Comment by pkalita-lbl** [comment]
Sure, I don't mind taking a look. Seth correctly pointed out that the place where the date is formatted is easy enough to change, but there may be knock on effects in other parts of the page that also need to be updated to account for the new format.
