### ISSUE TITLE
recent-news.md ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#52]
Hello, 

Are we doing this ? I thought we were not supporting the newsletters anymore. 

Also, the youtube video link is not working (see also my comment in the Google spreadsheet). 

I would remove this 

@thomaspd

**Comment by pgaudet** [comment]
Deleted

**Comment by kltm** [comment]
@pgaudet 
We will support news letters and the like.

**Comment by pgaudet** [comment]
@kltm 
With @lpalbou @thomaspd @suzialeksander 
we decided we didn't want to do that 


We can use the go-announcement repo- 

OK ?

**Comment by kltm** [comment]
@pgaudet 
What you have decided is okay, but the posts systems is integrated in jekyll and easy to use. The use of go-announcement seems to be a bit of a mis-fit for things like Ruth's Cariovascular updates, etc.

**Comment by RLovering** [comment]
I must admit that it was rather sad that the only news items ever listed seem to have been the UCL newsletters, so unless there is a future plan to invest the person power into creating news stories there doesn't seem much point in having a news section. But it is a shame that the twitter account isn't visible on the home page, especially as it is apparently very easy to include a feed ( I am sure you are aware of this but if not see our webpage which is also drupal based.) https://www.ucl.ac.uk/cardiovascular/research/pre-clinical-and-fundamental-science/functional-gene-annotation

I think you will get a lot more twitter followers if you have the feed actually on the home page, rather than expecting people to see the small twitter icon at the top and click on this to see what is there

Ruth

**Comment by lpalbou** [comment]
Hi @RLovering we do have a twitter link on the homepage but it is discreet (see upper right corner with facebook, github and agr icons) http://geneontology.org

Thanks for suggesting integrating a twitter feed/timeline, it is indeed [very easy to integrate](https://help.twitter.com/en/using-twitter/embed-twitter-feed).

We would have to check how this could fit the general design of the site, but we could give it a try. I'll let the PO @suzialeksander and @pgaudet decide.
