### ISSUE TITLE
Fix https://geneontology.github.io/docs/downloads/ including links

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#83]
https://geneontology.github.io/docs/downloads/

including links 

Thanks !

**Comment by lpalbou** [comment]
Is that what you wanted ?
https://github.com/geneontology/geneontology.github.io/pull/97

I can also write a documentation for BDbags, but perhaps it should be a different page since it will get more technical (some reference: https://github.com/fair-research/bdbag/blob/master/doc/cli.md)

To have a taste of how it would look like:

---

The following example requires both [python](https://www.python.org/downloads/) and [pip](https://pip.pypa.io/en/stable/installing/) to be installed. Once this is done, you can install the [BDBag cli](https://github.com/fair-research/bdbag) by following those steps:
```
pip install bdbag
git clone https://github.com/fair-research/bdbag
python setup.py install

check that you pass all tests:
python setup.py test
```

Once the [BDBag cli](https://github.com/fair-research/bdbag) is installed, fetch a DOI versioned of GO dataset, either the full archive or the holey bag. For this example, since we plan on accessing single files, the holey bag (containing only the references to our files) is sufficient. In your bdbag, a file named fetch.txt indicates all the files contained and accessible from this archive. Its syntax is as follow:

| URL | Length | Filename |
|-----|---------|----------|
| http://release.geneontology.org/2018-10-08/annotations/aspgd.gaf.gz | 6346222 | data/annotations/aspgd.gaf.gz |
| http://release.geneontology.org/2018-10-08/annotations/aspgd.gpad.gz | 4883110 | data/annotations/aspgd.gpad.gz |
| http://release.geneontology.org/2018-10-08/annotations/aspgd.gpi.gz | 1367586 | data/annotations/aspgd.gpi.gz |
...

The full extent of possible queries over BDbags are described [here](https://github.com/fair-research/bdbag/blob/master/doc/cli.md).

Assuming you are in your GO BDbag folder, you can for instance retrieve the first file (aspgd.gaf.gz) with two different methods:

## By the URL of the file
```
bdbag --resolve all --fetch-filter url==http://release.geneontology.org/2018-10-08/annotations/aspgd.gaf.gz ./
```

## By the name of the file
```
bdbag --resolve all --fetch-filter filename==data/annotations/aspgd.gaf.gz ./
```

The file retrieved will be stored in the same folder hierarchy as described in the filename. In the previous example, the file `aspgd.gaf.gz` retrieved will be stored locally in `data/annotations/`

**Notes**: 
* this specific file could be accessed by using `length==6346222` but there is no guaranty that this size is unique. The length filter is therefore better used to retrieve a set of files smaller than or greater than a certain threshold
* holey BDbags are a very convenient way to retrieve only the files important to you as the holey BDbags only contain the references needed to actually retrieve the files of interest

**Comment by kltm** [comment]
I think links to BDBags documentation/explanations are fine, but it's outside the core documentation that we want to maintain for our users ourselves.

**Comment by lpalbou** [comment]
Well, let's our product owner decide.

IMHO, we need to give at least one concrete example like this so users get the idea of what bdbags are and how they can actually use it to fetch their data.. Those are not (yet) conventional technologies.

However, this should probably be part of a more technical documentation, with other pages describing the howto of our API, SPARQL and Ribbon integration (already a thread on that one)

**Comment by kltm** [comment]
@selewis I'm happy to talk to you about this sometime (later) this week.

**Comment by lpalbou** [comment]
@pgaudet @selewis do we want this documentation for BDbag somewhere on the site and where ? It is kind of related to the bioinformatics guide we were discussing, except this is just for data retrieval

**Comment by selewis** [comment]
Yes I would think. Anything that helps people get to the data easily (one stop shop) is useful, and since data commons is using these we will need to document how to get it.

**Comment by suzialeksander** [comment]
It looks like this is done and is on https://geneontology.github.io/docs/tools-guide/, anything else before I close? @pgaudet I can't tell exactly what this ticket was about, please add if anything was missed.

**Comment by pgaudet** [comment]
We cam probably close, just a question about SVN access: can we really say we provide svn access ? We have a number of files there, all different dates: 
* gene_ontology.obo : released 4 hours ago (!) 
* go.obo 10 months ago 
* go-simple.obo 2 years ago (we don't explain why go-simple is in the doc). 

This seems very misleading !! 

Pascale

**Comment by lpalbou** [comment]
Good point, after checking the SVN access, I am really not sure this would be useful for any user  and we also discussed to deprecate SVN (https://github.com/geneontology/geneontology.github.io/issues/3).

Currently, only a few files in a few folders gets updated:
<img width="982" alt="Screen Shot 2019-08-12 at 6 10 55 AM" src="https://user-images.githubusercontent.com/24249870/62867356-f36c8500-bcc7-11e9-803e-2cb3d6988de4.png">

@kltm @cmungall how about removing the SVN access links on the go website or moving them to [Archived Data](https://geneontology.github.io/docs/archives/) ? This will prepare the way to deprecate SVN access later on. We probably need to clarify also in the documentation how to access previous releases (cf https://github.com/geneontology/geneontology.github.io/pull/145#issuecomment-520382796)

**Comment by suzialeksander** [comment]
I think we're best off killing any mention of SVN, no? @kltm

**Comment by kltm** [comment]
At this point, there is little reason for a "regular user" to know anything about our SVN. I'd be happy for it to start disappearing from documentation.

**Comment by pgaudet** [comment]
I removed the link form the downloads page, and added it to the /archives page.
